name: seconed workflow
on: 
    push: 
        branches:
            - main
        paths:
            - "src/**"
    
    pull_request:
        branches: 
            - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: |
                ls -la
                echo "This is a test job for the second workflow"
